# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leipzig', '0033_setting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AlterField(
            model_name='article',
            name='committee_tag',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='external_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='image_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='team',
            field=models.CharField(choices=[(b'OT', b'Organising Team'), (b'MT', b'Media Team')], max_length=2),
        ),
        migrations.AlterField(
            model_name='house',
            name='cite',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='image_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='quote',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songwish',
            name='spotify_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songwish',
            name='video_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='image_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
