# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leipzig', '0034_auto_20151206_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='app_analytics',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='app_meta_description',
            field=models.TextField(blank=True),
        ),
    ]
