# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leipzig', '0036_auto_20151207_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='app_chrome_navbar_theme_hex_colour',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
