# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leipzig', '0037_setting_app_chrome_navbar_theme_hex_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='app_chrome_navbar_theme_hex_colour',
            new_name='app_chrome_navbar',
        ),
    ]
