# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leipzig', '0039_auto_20151207_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('tagline', models.TextField(blank=True)),
                ('rank', models.IntegerField(blank=True)),
                ('image_link', models.URLField()),
            ],
        ),
    ]
