# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leipzig', '0043_auto_20160516_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, upload_to=b'team_pictures/'),
        ),
    ]
